### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Larkin-man** [Larkin-man/2D-Location-Editor#2]
- [ ] диздок
- [ ] удаление указанного даже не в этой ячейке
- [ ] по умолчанию позиция масштаба 11
- [ ] инструменты конфликтуют
- [ ] экспорт карты
- [ ] инфа о локе - спрайты
- [ ] когда удаляешь, то от размера можно перерисовать сосед ячейку
- [ ] отменить последний спрайт
- [x] 	нажатие средней кнопки в сером поле
- [x] 	открывание спрайтов
- [x] 	отменить тайл
- [x] 	новый - там рисуется стор
- [x] 	удаление одного последнего
- [x] 	нижние тайлы перерисовка
- [x] 	инфо на крестике подсказка
